### ISSUE TITLE
Route from form submit error in webworker-mode

### ISSUE THREAD

**Issue by vaseker** [alexpods/angular2-universal-starter#50]
Hello.
I have an error when submitting form using `Enter` key and trying to route using form input, but if event happens from `input[type="submit"].click()`, its okay. 
In some cases `submit` event doesn't fire at all.
And form submits works fine in not-worker mode.

Error is 
> TypeError: null is not an object (evaluating 'element.events')

Code sample:
```typescript
import { Component } from 'angular2/core';
import { NgForm } from 'angular2/common';
import { Router } from 'angular2/router';

@Component({
    selector: 'test-form',
    directives: [NgForm],
    template: `<form (ngSubmit)="onSubmit()">
    <input [(ngModel)]="field" placeholder="Type here smth" />
    <input type="submit" value="go" />
</form>`
})

export class ListComponent {
    field: string = '';

    constructor(private _router: Router) {};

    onSubmit() {
        this._router.navigate( ['SomeRoute', { param: this.field }] );
    }
}

```

**Comment by vaseker** [comment]
Got source of issue
> EXCEPTION: TypeError: Cannot read property 'events' of null
STACKTRACE:
TypeError: Cannot read property 'events' of null
    at WebWorkerRootRenderer._dispatchEvent (http://localhost:8080/worker_app.js:829:21)
    at Object.next (http://localhost:8080/worker_app.js:818:88)

Which is a part of angular2 package. Moving issue to angular2.
