### ISSUE TITLE
Serverside rendering is not working?

### ISSUE THREAD

**Issue by Kunepro** [alexpods/angular2-universal-starter#59]
In constant.js both values are already set to true and therefore server side rendering should work.
However if I disable JS nothing gets rendered, and if I enable JS the screen is blank until the browser has finished loading the JS. Both behaviour suggest that server-side is not working.
I did `npm install`, however this is mu error.log:
```
2016-05-11 21:34 +01:00: module.js:341
    throw err;
    ^

Error: Cannot find module '/Users/Kzyl-Orda/Projects/Tests/angular2-universal-starter/node_modules/pm2/lib/ProcessContainerFork.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
```

**Comment by ianbelcher** [comment]
I'm seeing the same thing. There doesn't appear to be any rendered content within either the `home` or `worker` routes. It is only populated on the client side after all the dependencies have loaded.
