### ISSUE TITLE
pm2 errors

### ISSUE THREAD

**Issue by bkinsey808** [alexpods/angular2-universal-starter#6]
Hi, I can run this directly and it works great with 
```
node dist/private/app.js
```

but when i try to run it with
```
npm start
```

The app doesn't start, and the error log fills up with errors:

```
Error: Cannot find module '/home/bkinsey/opt/alexpods/angular2-universal-starter/dist/private/app.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function._load (/home/bkinsey/opt/alexpods/angular2-universal-starter/node_modules/pmx/lib/transaction.js:62:21)
    at Object.<anonymous> (/home/bkinsey/opt/alexpods/angular2-universal-starter/node_modules/pm2/lib/ProcessContainerFork.js:28:21)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
Error: Cannot find module '/home/bkinsey/opt/alexpods/angular2-universal-starter/dist/private/app.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function._load (/home/bkinsey/opt/alexpods/angular2-universal-starter/node_modules/pmx/lib/transaction.js:62:21)

[...]
```

**Comment by alexpods** [comment]
Hmm, right now I don't know the cause of this error. I'm going to elaborate on this.
Could you run `$(npm bin)/pm2 show all` and send me results?

Right now I think you should do `npm restart` and everything will be fine.

**Comment by alexpods** [comment]
Also pull the latest version of the repo and make `npm restart`.
I think this will solve the problem.

**Comment by bkinsey808** [comment]
The latest pull fixed the bugs in the log. But I can't figure out what port the app is supposed to be running when i run it with pm2. Is that coming from ecosystem.json?
It is not running on `http://localhost:3000/` or `http://localhost:8000/`

show all returns this:

```
[PM2][WARN] all doesn't exist
```

**Comment by alexpods** [comment]
It's in `ecosystem.json`, environment variable `PORT`. I use it [here](https://github.com/alexpods/angular2-universal-starter/blob/master/src/server/boot.ts#L4) then.

I gave you a wrong command. Now it should be `npm run show`.

**Comment by bkinsey808** [comment]
```
> angular2-universal-starter@0.1.0 show /home/bkinsey/opt/bkinsey808/angular2-universal-starter
> pm2 show $(node -e "console.log(require('./ecosystem.json').name)")

Describing process with id 0 - name angular2-universal-starter
┌───────────────────┬─────────────────────────────────────────────────────────────────────────────┐
│ status            │ online                                                                      │
│ name              │ angular2-universal-starter                                                  │
│ id                │ 0                                                                           │
│ path              │ /home/bkinsey/opt/bkinsey808/angular2-universal-starter/dist/private/app.js │
│ args              │                                                                             │
│ exec cwd          │ /home/bkinsey/opt/bkinsey808/angular2-universal-starter                     │
│ error log path    │ /home/bkinsey/opt/bkinsey808/angular2-universal-starter/logs/errors-0.log   │
│ out log path      │ /home/bkinsey/opt/bkinsey808/angular2-universal-starter/logs/output-0.log   │
│ pid path          │ /home/bkinsey/.pm2/pids/angular2-universal-starter-0.pid                    │
│ mode              │ fork_mode                                                                   │
│ node v8 arguments │                                                                             │
│ watch & reload    │ ✔                                                                           │
│ interpreter       │ node                                                                        │
│ restarts          │ 2                                                                           │
│ unstable restarts │ 0                                                                           │
│ uptime            │ 20m                                                                         │
│ created at        │ 2016-01-15T08:51:46.539Z                                                    │
└───────────────────┴─────────────────────────────────────────────────────────────────────────────┘
Process configuration

Revision control metadata
┌──────────────────┬──────────────────────────────────────────────────────────┐
│ revision control │ git                                                      │
│ remote url       │ https://github.com/bkinsey808/angular2-universal-starter │
│ repository root  │ /home/bkinsey/opt/bkinsey808/angular2-universal-starter  │
│ last update      │ 2016-01-15T09:12:25.227Z                                 │
│ revision         │ 8cb0ec82f194a06090d2e0e8412156798d3df0f7                 │
│ comment          │ Merge branch 'master' into app-case-fix                  │
│ branch           │ app-case-fix                                             │
└──────────────────┴──────────────────────────────────────────────────────────┘
Probes value
┌────────────┬────────┐
│ Loop delay │ 1.96ms │
└────────────┴────────┘

```

**Comment by bkinsey808** [comment]
ok, that's what I thought. then is should be port 3000. Chrome says: 

```
This webpage is not available

ERR_CONNECTION_REFUSED
```

**Comment by alexpods** [comment]
Hmm, could you
```bash
git checkout master
git pull origin master
npm restart
```
And then tell me whether you still have any problems or not.

**Comment by alexpods** [comment]
Try also 127.0.0.1:3000. Maybe there's some problem with host resolution.

**Comment by bkinsey808** [comment]
Same result. neither `127.0.0.1:3000` nor `http://localhost:3000/` works. But `http://localhost:8000/` works when I run `node dist/private/app.js`

**Comment by alexpods** [comment]
Do you have anything in error or output logs? If you do - send me, please.

**Comment by bkinsey808** [comment]
error log is empty since your fix. output log says
```
Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
```

**Comment by alexpods** [comment]
Could you switch off the watch mode for `pm2` (set "watch" in pm2 file to `false`). Then `npm restart`.

This is not a good solution. But if it works we'll understand the cause of the problem.

**Comment by bkinsey808** [comment]
I pulled the latest code and it works now. Love this project, thanks!
